# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_auto_20181201_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthsinauser',
            name='access_token',
            field=models.CharField(db_index=True, max_length=64, verbose_name='access_token'),
        ),
    ]
